const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.hash.slice(1));if(params.get('key'))sessionStorage.setItem('agentgit-viewer',params.get('key'));history.replaceState(null,'',location.pathname);
let token=sessionStorage.getItem('agentgit-viewer')||'',room=null,tab='overview';
const labels={overview:'房间概览',proposals:'项目提案',tasks:'任务收件箱',events:'活动记录',setup:'连接 Codex'};
const names={'member.joined':'加入了房间','proposal.submitted':'提交了项目提案','proposal.revised':'更新了项目提案','task.dispatched':'验证任务已派发','task.delivered':'Relay 已收到任务','task.read':'任务已通过工具读取'};
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500);}
async function refresh(){if(!token){render();return;}try{const res=await fetch('/api/room',{headers:{Authorization:'Bearer '+token}});const data=await res.json();if(!res.ok)throw Error(data.error);room=data;$('#connection').textContent='● Host 在线';$('#nav-count').textContent=new Set(room.proposals.map(p=>p.member_id)).size;render();}catch(e){$('#connection').textContent='○ 未同步';toast(e.message);if(!room)render();}}
const member=id=>room.members.find(m=>m.id===id);
const latest=()=>room.proposals.filter((p,i,a)=>a.findIndex(q=>q.member_id===p.member_id)===i);
function cards(){return latest().map(p=>`<article class="card"><div class="card-top"><span class="avatar">${escape(member(p.member_id)?.name[0])}</span><div><strong>${escape(member(p.member_id)?.name)}</strong><small>项目提案 · v${p.revision} ${member(p.member_id)?.fixture?'· 样例':''}</small></div></div><p>${escape(p.body.slice(0,155))}${p.body.length>155?'…':''}</p><button data-proposal="${p.id}">查看完整提案 ↗</button></article>`).join('')||'<div class="empty">还没有提案。在 Codex 内准备并提交第一份想法。</div>';}
function activity(){return room.events.slice(-12).reverse().map(e=>`<div class="row"><div><strong>${escape(member(e.payload.member_id)?.name||'Host')} ${escape(names[e.type]||e.type)}</strong><p>${escape(e.type)} · #${e.seq}</p></div><code>${new Date(e.created_at).toLocaleTimeString('zh-CN')}</code></div>`).join('')||'<div class="empty">暂无活动</div>';}
function render(){ $('#breadcrumb').textContent=labels[tab];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
  if(!token||!room){$('#main').innerHTML=`<div class="eyebrow">AGENTGIT / LOCAL WORKSPACE</div><h1>让团队从同一页开始。</h1><p class="lead">连接队长房间，查看每个人明确提交的想法。</p><div class="notice">在项目终端运行 <code>npm run demo</code>，获得带访问凭据的本地房间入口。</div><form id="connect"><label for="key">房间查看凭据</label><input id="key" type="password" autocomplete="off" required><button class="primary">打开房间</button></form>`;$('#connect').onsubmit=e=>{e.preventDefault();token=$('#key').value;sessionStorage.setItem('agentgit-viewer',token);refresh();};return;}
  const head=`<div class="eyebrow">WORKSPACE / ${escape(room.room_id.slice(0,8).toUpperCase())}</div>`;
  if(tab==='overview')$('#main').innerHTML=head+`<div class="heading"><div><h1>把各自的想法，带到一起。</h1><p class="lead">先提案，再共识。这里是团队共同的起点。</p></div><span class="badge green">提案收集中</span></div><div class="pipeline">${['个人提案','共同定案','任务规划','联合审核','并行开发'].map((s,i)=>`<div class="step ${i===0?'current':''}"><b>${i+1}</b>${s}</div>`).join('')}</div><div class="stats"><div class="stat"><span>房间成员</span><strong>${room.members.length}</strong><span>包含明确标记的样例成员</span></div><div class="stat"><span>已提交提案</span><strong>${latest().length} <span>/ ${room.members.length}</span></strong><span>保留正文和全部历史版本</span></div><div class="stat"><span>当前阶段</span><strong>收集</strong><span>尚未共同定案</span></div></div><div class="heading"><h2>每个人的项目提案</h2><button data-go="proposals">查看全部 →</button></div><div class="grid">${cards()}</div><div class="notice">M0 验证版 · 样例仅用于体验页面。真实提案从 Codex 工具提交；共同定案、自动审核和正式开工尚未开放。</div><section class="section"><div class="heading"><h2>最近活动</h2><span class="subtle">每 5 秒同步</span></div>${activity()}</section>`;
  if(tab==='proposals')$('#main').innerHTML=head+`<h1>项目提案</h1><p class="lead">保留不同观点，也保留它们的来源。</p><div class="grid">${cards()}</div><section class="section"><h2>提交历史</h2>${room.proposals.map(p=>`<div class="row"><div><strong>${escape(member(p.member_id)?.name)} · v${p.revision}</strong><p>${escape(p.content_hash.slice(0,20))}…</p></div><button data-proposal="${p.id}">查看正文</button></div>`).join('')}</section>`;
  if(tab==='tasks')$('#main').innerHTML=head+`<h1>任务收件箱</h1><p class="lead">送达、读取和开始执行，是三个不同状态。</p><div class="notice">以下均为 M0 验证任务，不包含代码修改权限。请在 Codex 内调用读取任务工具。</div>${room.tasks.map(t=>`<div class="row"><div><strong>验证原生任务读取 <span class="badge">Fixture</span></strong><p>${escape(member(t.member_id)?.name)} · ${escape(t.id.slice(0,8))}</p></div><span class="badge ${t.read?'green':''}">${t.read?'工具已读取':t.delivered?'Relay 已送达':'等待 Relay'}</span></div>`).join('')}<div class="notice">正式任务分发：尚未开放。<br>开工许可：未签发。</div>`;
  if(tab==='events')$('#main').innerHTML=head+`<h1>活动记录</h1><p class="lead">只记录明确提交的产物与协作事件。</p>${activity()}`;
  if(tab==='setup')$('#main').innerHTML=head+`<h1>在 Codex 里继续。</h1><p class="lead">计划留在原会话，确认后的产物进入团队房间。</p><div class="two"><article class="card"><h3>01　启动本地桥接</h3><p>在成员电脑的项目目录启动 Relay，再运行安装脚本配置本地 MCP。</p><pre class="code">npm run relay\n.\\scripts\\Install-AgentGit.ps1</pre></article><article class="card"><h3>02　加入与提交</h3><p>在新的 Codex 会话中，用队长提供的邀请加入；准备提案，核对预览，然后提交。</p><pre class="code">使用 AgentGit 加入房间。\n准备我的项目提案预览。\n确认后提交这个版本。\n读取我的验证任务。</pre></article></div><div class="notice">邀请信息保存在队长电脑 .agentgit/host/access.json。此页面使用只读查看凭据，不展示邀请密钥。<br>需要真正的 Plan 时，请通过运行端原生入口切换。安装后需新开会话加载 MCP。</div><h2>本版能力</h2>${[['冻结正文 / SHA-256','已实现'],['幂等回执 / SQLite 恢复','已实现'],['Relay 收件 / HTTP 补收','已实现'],['真实原生 Plan 全流程','待实机验证'],['WSS / 自动 Coordinator / Hooks','后续版本']].map(([a,b])=>`<div class="row"><span>${a}</span><span class="badge">${b}</span></div>`).join('')}`;
  document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{tab=b.dataset.go;render();});document.querySelectorAll('[data-proposal]').forEach(b=>b.onclick=()=>{const p=room.proposals.find(p=>p.id===b.dataset.proposal);$('#detail-title').textContent=member(p.member_id)?.name+' · 项目提案 v'+p.revision;$('#detail-body').textContent=p.body;$('#detail-meta').textContent='SHA-256 '+p.content_hash+' · '+p.created_at;$('#detail').showModal();});
}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});$('#refresh').onclick=refresh;$('#close-detail').onclick=()=>$('#detail').close();refresh();setInterval(()=>{if(!$('#detail').open&&token)refresh();},5000);
