export const EVENT_TYPES = {
  PROJECT_INITIALIZED: "project.initialized",
  TASK_ACCEPTED: "task.accepted",
  TASK_STATUS_CHANGED: "task.status_changed",
  TASK_READY: "task.ready",
  PROPOSAL_SUBMITTED: "proposal.submitted",
  CONSENSUS_CREATED: "consensus.created",
  CONSENSUS_REVISED: "consensus.revised",
  CONSENSUS_CONFIRMED: "consensus.confirmed",
  CONSENSUS_OBJECTED: "consensus.objected",
  CONSENSUS_PUBLISHED: "consensus.published",
  MODULE_CLAIMED: "module.claimed",
  WORK_UNIT_ACCEPTED: "work_unit.accepted",
  WORK_UNIT_READY: "work_unit.ready",
  WORK_UNIT_STATUS_CHANGED: "work_unit.status_changed",
  PLAN_REVIEW_RECORDED: "plan_review.recorded",
  IDEA_REVIEW_RECORDED: "idea_review.recorded",
  ISSUE_REPORTED: "issue.reported",
  MILESTONE_COMPLETED: "milestone.completed",
  FREEZE_EXCEPTION_CREATED: "freeze_exception.created",
  FREEZE_EXCEPTION_DECIDED: "freeze_exception.decided",
  MODULE_ACCEPTED: "module.accepted",
  EXECUTION_DECISION_CREATED: "execution_decision.created",
  EXECUTION_DECISION_ACKNOWLEDGED: "execution_decision.acknowledged",
  EVIDENCE_SUBMITTED: "evidence.submitted",
  EVIDENCE_REVIEWED: "evidence.reviewed",
  CHANGE_CREATED: "requirement.change_created",
  CHANGE_APPROVED: "requirement.change_approved",
  CHANGE_REJECTED: "requirement.change_rejected",
  REQUIREMENT_REVISED: "requirement.revised",
  CONFLICT_CREATED: "conflict.created",
  CONFLICT_RESOLVED: "conflict.resolved",
  CONFLICT_REVIEW_QUEUED: "conflict_review.queued",
  CONFLICT_REVIEW_STARTED: "conflict_review.started",
  CONFLICT_REVIEW_COMPLETED: "conflict_review.completed",
  CONFLICT_REVIEW_FAILED: "conflict_review.failed",
  LEASE_ISSUED: "execution.lease_issued",
  EXECUTION_COMMAND_QUEUED: "execution.command_queued",
  EXECUTION_COMMAND_CLAIMED: "execution.command_claimed",
  EXECUTION_COMMAND_UPDATED: "execution.command_updated",
  RELAY_HEARTBEAT: "relay.heartbeat"
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];

export const TASK_TRANSITIONS = {
  TODO: ["PLANNING", "BLOCKED"],
  PLANNING: ["READY", "BLOCKED"],
  READY: ["IN_PROGRESS", "BLOCKED", "PLANNING"],
  IN_PROGRESS: ["BLOCKED", "WAITING_REVIEW"],
  BLOCKED: ["PLANNING", "IN_PROGRESS"],
  WAITING_REVIEW: ["IN_PROGRESS", "DONE", "BLOCKED"],
  DONE: []
} as const;
