import { createApp } from "vue";
import { createPinia } from "pinia";
import "@fontsource/dm-sans/latin-400.css";
import "@fontsource/dm-sans/latin-500.css";
import "@fontsource/dm-sans/latin-600.css";
import "@fontsource/ibm-plex-mono/latin-400.css";
import App from "./App.vue";
import { router } from "./router";
import "./style.css";
createApp(App).use(createPinia()).use(router).mount("#app");
